CREATE TABLE `primerageneracion_base` (
  `ID` int(11),
  `Nombre` varchar(30),
  `TipoElemental1` varchar(15),
  `TipoElemental2` varchar(15),
  `Habitat` varchar(15),
  `ColorPokemon` varchar(10)
)

INSERT INTO `primerageneracion_base` (`ID`, `Nombre`, `TipoElemental1`, `TipoElemental2`, `Habitat`, `ColorPokemon`) VALUES
(1, 'bulbasaur', 'planta', 'veneno', 'pradera', 'verde'),
(2, 'charmander', 'fuego', 'ninguno', 'montaña', 'rojo'),
(3, 'squirtle', 'agua', 'ninguno', 'agua dulce', 'azul'),
(4, 'caterpie', 'bicho', 'ninguno', 'bosque', 'verde'),
(5, 'weedle', 'bicho', 'veneno', 'bosque', 'marron'),
(6, 'pidgey', 'normal', 'volador', 'bosque', 'marron'),
(7, 'rattata', 'normal', 'ninguno', 'pradera', 'morado'),
(8, 'spearow', 'normal', 'volador', 'campo', 'marron'),
(9, 'ekans', 'veneno', 'ninguno', 'pradera', 'morado'),
(10, 'pikachu', 'electrico', 'ninguno', 'bosque', 'amarillo'),
(11, 'sandshrew', 'tierra', 'ninguno', 'campo', 'amarillo'),
(12, 'nidoran-f', 'veneno', 'ninguno', 'pradera', 'azul'),
(13, 'nidoran-m', 'veneno', 'ninguno', 'pradera', 'morado'),
(14, 'clefairy', 'hada', 'ninguno', 'montaña', 'rosa'),
(15, 'vulpix', 'fuego', 'ninguno', 'pradera', 'marron'),
(16, 'jigglypuff', 'normal', 'hada', 'pradera', 'rosa'),
(17, 'zubat', 'veneno', 'volador', 'caverna', 'morado'),
(18, 'oddish', 'planta', 'veneno', 'pradera', 'azul'),
(19, 'paras', 'bicho', 'planta', 'bosque', 'rojo'),
(20, 'venonat', 'bicho', 'veneno', 'bosque', 'morado'),
(21, 'diglett', 'tierra', 'ninguno', 'caverna', 'marron'),
(22, 'meowth', 'normal', 'ninguno', 'ciudad', 'amarillo'),
(23, 'psyduck', 'agua', 'ninguno', 'agua dulce', 'amarillo'),
(24, 'mankey', 'lucha', 'ninguno', 'montaña', 'marron'),
(25, 'growlithe', 'fuego', 'ninguno', 'pradera', 'marron'),
(26, 'poliwag', 'agua', 'ninguno', 'agua dulce', 'azul'),
(27, 'abra', 'psiquico', 'ninguno', 'ciudad', 'marron'),
(28, 'machop', 'lucha', 'ninguno', 'montaña', 'gris'),
(29, 'bellsprout', 'planta', 'veneno', 'bosque', 'verde'),
(30, 'tentacool', 'agua', 'veneno', 'agua salada', 'azul'),
(31, 'geodude', 'roca', 'tierra', 'montaña', 'marron'),
(32, 'ponyta', 'fuego', 'ninguno', 'pradera', 'amarillo'),
(33, 'slowpoke', 'agua', 'psiquico', 'agua dulce', 'rosa'),
(34, 'magnemite', 'electrico', 'acero', 'campo', 'gris'),
(35, 'farfetchd', 'normal', 'volador', 'pradera', 'marron'),
(36, 'doduo', 'normal', 'volador', 'pradera', 'marron'),
(37, 'seel', 'agua', 'ninguno', 'agua salada', 'blanco'),
(38, 'grimer', 'veneno', 'ninguno', 'ciudad', 'morado'),
(39, 'shellder', 'agua', 'ninguno', 'agua salada', 'morado'),
(40, 'gastly', 'fantasma', 'veneno', 'caverna', 'morado'),
(41, 'onix', 'roca', 'tierra', 'caverna', 'gris'),
(42, 'drowzee', 'psiquico', 'ninguno', 'pradera', 'amarillo'),
(43, 'krabby', 'agua', 'ninguno', 'agua dulce', 'rojo'),
(44, 'voltorb', 'electrico', 'ninguno', 'ciudad', 'rojo'),
(45, 'exeggcute', 'planta', 'psiquico', 'bosque', 'rosa'),
(46, 'cubone', 'tierra', 'ninguno', 'montaña', 'marron'),
(47, 'hitmonlee', 'lucha', 'ninguno', 'ciudad', 'marron'),
(48, 'lickitung', 'normal', 'ninguno', 'pradera', 'rosa'),
(49, 'koffing', 'veneno', 'ninguno', 'ciudad', 'morado'),
(50, 'rhyhorn', 'tierra', 'roca', 'campo', 'gris'),
(51, 'chansey', 'normal', 'ninguno', 'ciudad', 'rosa'),
(52, 'tangela', 'planta', 'ninguno', 'pradera', 'azul'),
(53, 'kangaskhan', 'normal', 'ninguno', 'pradera', 'morado'),
(54, 'horsea', 'agua', 'ninguno', 'agua salada', 'azul'),
(55, 'goldeen', 'agua', 'ninguno', 'agua dulce', 'rojo'),
(56, 'staryu', 'agua', 'ninguno', 'agua salada', 'marron'),
(57, 'mr-mime', 'psiquico', 'hada', 'ciudad', 'rosa'),
(58, 'scyther', 'bicho', 'volador', 'pradera', 'verde'),
(59, 'jynx', 'hielo', 'psiquico', 'ciudad', 'rojo'),
(60, 'electabuzz', 'electrico', 'ninguno', 'pradera', 'amarillo'),
(61, 'magmar', 'fuego', 'ninguno', 'montaña', 'rojo'),
(62, 'pinsir', 'bicho', 'ninguno', 'bosque', 'marron'),
(63, 'tauros', 'normal', 'ninguno', 'pradera', 'marron'),
(64, 'magikarp', 'agua', 'ninguno', 'agua dulce', 'rojo'),
(65, 'lapras', 'agua', 'hielo', 'agua salada', 'azul'),
(66, 'ditto', 'normal', 'ninguno', 'ciudad', 'morado'),
(67, 'eevee', 'normal', 'ninguno', 'ciudad', 'marron'),
(68, 'porygon', 'normal', 'ninguno', 'ciudad', 'rosa'),
(69, 'omanyte', 'roca', 'agua', 'agua salada', 'azul'),
(70, 'kabuto', 'roca', 'agua', 'agua dulce', 'marron'),
(71, 'aerodactyl', 'roca', 'volador', 'montaña', 'morado'),
(72, 'snorlax', 'normal', 'ninguno', 'montaña', 'negro'),
(73, 'articuno', 'hielo', 'volador', 'raro', 'azul'),
(74, 'zapdos', 'electrico', 'volador', 'raro', 'amarillo'),
(75, 'moltres', 'fuego', 'volador', 'raro', 'amarillo'),
(76, 'dratini', 'dragon', 'ninguno', 'agua dulce', 'azul'),
(77, 'mewtwo', 'psiquico', 'ninguno', 'raro', 'morado'),
(78, 'mew', 'psiquico', 'ninguno', 'raro', 'rosa');

ALTER TABLE `primerageneracion_base` ADD PRIMARY KEY (`ID`);

ALTER TABLE `primerageneracion_base` MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
